### ISSUE TITLE
Add official motions to seed OR load it from the database dump

### ISSUE THREAD

**Issue by shippy** [PiechZ/greybox_wrapped#113]
Currently, we work around trying to figure out which motions are "official" (i.e. announced and prepared) by providing a seed CSV `official_teze_id` and using it in `base__debata.sql`. To update for the next year, we need to either:

1. Update the seed file, or
2. Update the logic that determines official motions.

**Comment by shippy** [comment]
I think I've got the data for (2) - although it adds a different manual step to get around an export error (Meltano's `target-duckdb` doesn't like a double-primary-key table like `soutez_teze`, it seems) - but that means it should be trivial to get the update for (1).

One potential issue is that right now, we're assuming motions are either official or they're not, but that's not the case - they're official _for a given competition_. So the new logic should contend with that.

**Comment by PiechZ** [comment]
I did (1) in PR #116.

About the (2):
My idea is, that you can get the list of official motions from table `soutez_teze`. Here you have `soutez_id `and `teze_id`.

When evaluating debate from `debtata `table, you can join the `soutez_teze ` table and if `teze_id ` is the same as `soutez_id`, the bonification can apply.

**Comment by shippy** [comment]
(2) implemented in #118.
