### ISSUE TITLE
Restyle the fonts and texts in frontend for better mobile phone experience

### ISSUE THREAD

**Issue by PiechZ** [PiechZ/greybox_wrapped#57]

**Comment by shippy** [comment]
Setting `fontSizes` in theme as per [docs](https://formidable.com/open-source/spectacle/docs/themes/) doesn't seem to help. Setting direct `fontSize="3em"` property on the Slide tags does, but it seems like there should be a better way.

**Comment by shippy** [comment]
I've been going about it wrong - `theme` refers to reference classes, not fonts directly, so the way to change them is:

```javascript
    fontSizes: {
      header: "3.5em",
      paragraph: "1.5em",
      text: "1.2em",
    },
```

and then `<Heading fontSize="header">`.

I'll leave it up to @szymsza to pick the responsive sizes - `em`s seem to work in my testing, but there might be a better best practice?

**Comment by shippy** [comment]
To summarize:

## Must-haves

- [ ] responsive font sizing in not-pixels (already drafted as noted above, but maybe it could be done better?)

## Nice-to-haves

- [ ] automated font fitting into the viewport (I think Spectacle might have some tag to use here?)
- [ ] horizontal/vertical centering of the viewport (currently, it sticks to top/left, depending on which dimension is bigger)

**Comment by szymsza** [comment]
See https://github.com/PiechZ/greybox_wrapped/pull/73
