### ISSUE TITLE
Align the dot-navigation in the middle

### ISSUE THREAD

**Issue by shippy** [PiechZ/greybox_wrapped#71]
Currently, the dot-navigation is hard-coded at `left = 45%`, which is good enough when there's around 5 achievements, but clearly off to the side when there's 10. There should be a simple way of centering it.

**Comment by shippy** [comment]
Example from id=2956: 
![image](https://user-images.githubusercontent.com/1340280/232252655-d1fdbb86-29a1-47b5-a41a-f99e82e5d024.png)

**Comment by szymsza** [comment]
See https://github.com/PiechZ/greybox_wrapped/pull/73
