### ISSUE TITLE
People with no achievements

### ISSUE THREAD

**Issue by szymsza** [PiechZ/greybox_wrapped#74]
When the API returns no achievements, the frontend currently gets stuck on `Loading...` forever. Something smarter would be preferable.

**Comment by PiechZ** [comment]
My suggestion:
"Zde se bohužel něco pokazilo, prosím, zkuste to jindy."
or
"Bohužel pro Vás žádné achievementy nemáme 😢. Aplikace je zatím v první fázi testování, budeme doplňovat další achievementy postupně. Zkuste to třeba příští rok."

@szymsza @shippy

**Comment by shippy** [comment]
Teď to nerozlišuje, jestli ta API odpověď ještě nepřišla, nelze ji vzít, nebo přišla prázdná. První je loading (máme), druhý je porucha (Zbyňka první message), třetí je smůlička (Zbyňka druhá message) - ale abychom ty messages nasadili, musíme nejdřív implementovat to rozlišení.

Z hlediska obsahu: nemáme zprávy pro někoho s nula oddebatovanými nebo odrozhodovanými debatami v tomto roce - takže buď alumnus nebo kouč. Dávalo by smysl směřovat tu smůlička zprávu jim?

**Comment by PiechZ** [comment]
Ano, asi jo.  Půjde asi o kouče, alumni, a pak debatéry s +- třemi debatami.
